---
title: "MP3"
author: "Sameera Jhunjhunwala, Zoya Alam, Khulood Fahim"
date: "4/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(macleish)
library(tidyverse)
library(tidycensus)
library(sf)
library(ggplot2)
library(leaflet)
library(dplyr)
library(sp)
```

```{r}
#install.packages("lwgeom")
macleish_layers %>% 
  pluck("trails")
```

```{r}
boundaries_aea <- macleish_layers %>% 
  pluck("boundary")

mac_forest <- macleish_layers %>% 
  pluck("forests") %>% 
  mutate(computed_area = st_area(geometry)) %>% 
  arrange(desc(computed_area))
```

```{r}
leaflet() %>% 
  addTiles() %>% 
  addPolygons(data = macleish_layers[["forests"]],
               weight = 1, popup = ~Sheet1__Na) %>% 
  addPolylines(data = forests_buffer) %>% 
  addPolylines(data = pluck(macleish_layers, "streams"), 
               weight = 1, color = "red") %>% 
  addPolylines(data = stream_buffer)
```

```{r}
stream_buffer <- macleish_layers %>% 
  pluck("streams") %>%
  st_transform(4326)

leaflet() %>% 
  addTiles() %>% 
  addPolylines(data = pluck(macleish_layers, "streams"), 
               weight = 1, color = "black") %>% 
  addPolylines(data = stream_buffer)
```

```{r}
buildings_buffer <- macleish_layers %>% 
  pluck("buildings") %>%
  st_transform(4326)

leaflet() %>% 
  addTiles() %>% 
  addPolylines(data = pluck(macleish_layers, "buildings"), 
               weight = 1, color = "brown") %>% 
  addPolylines(data = buildings_buffer)
```

```{r}
trails_buffer <- macleish_layers %>% 
  pluck("trails") %>%
  st_transform(4326)

leaflet() %>% 
  addTiles() %>% 
  addPolylines(data = pluck(macleish_layers, "trails"), 
               weight = 1, label = ~name, color = ~color) %>% 
  addPolylines(data = trails_buffer)
```

```{r}
forests_buffer <- macleish_layers %>% 
  pluck("forests") %>%
  st_transform(4326)

leaflet() %>% 
  addTiles() %>% 
  addPolylines(data = pluck(macleish_layers, "forests"), 
               weight = 1, color = "black") %>% 
  addPolylines(data = forests_buffer)
```

```{r}
intersections <- macleish_layers %>%
  pluck("trails") %>%
  st_intersection(pluck(macleish_layers ,"streams"))
```

```{r}
intersections_forest_streams <- macleish_layers %>%
  pluck("forests") %>%
  st_intersection(pluck(macleish_layers ,"streams"))
```


```{r}
my_points <- tribble(
  ~point, ~lat, ~lon,
  "A", -72.682988, 42.449998,
  "B", -72.682533, 42.450209,
  "C", -72.682420, 42.452236,
  "D", -72.682426, 42.452888,
  "E", -72.682950, 42.454380,
  "F", -72.684968, 42.455187
)
```

```{r}
my_sf <- my_points %>%
  st_as_sf(coords = c("lat", "lon"))
```

```{r}
# 
macleish_layers %>%
  leaflet() %>%
  addTiles() %>%
  addPolygons(data = macleish_layers[["boundary"]], weight = 2, fillOpacity = 0.01) %>%
  addPolygons(data = macleish_layers[["forests"]], weight = 4, color = ~forest_pal, popup = ~Sheet1__Na) %>%
  addPolylines(data = pluck(macleish_layers, "streams"), 
               weight = 2, color = "black") %>% 
  addPolygons(data = pluck(macleish_layers, "buildings"), 
               weight = 2, color = "dark red") %>% 
  addPolylines(data = macleish_layers[["forests"]],
               weight = 1, popup = ~Sheet1__Na) %>% 
  addPolylines(data = pluck(macleish_layers, "trails"), 
               weight = 1, color = ~color) %>% 
  addPolylines(data = my_points, lat = ~lon, lng = ~lat) %>%  
  #addMarkers(data = st_cast(intersections, "POINT"), popup = ~name ) %>% 
  addMarkers(data = my_sf, popup = ~point) %>% 
  addPolygons(data = macleish_layers[["research"]], weight = 1) 
```



